### ISSUE TITLE
 [ERROR] unreleasable file 

### ISSUE THREAD

**Issue by xjchenhao** [fex-team/fis3-postpackager-loader#13]
![image](https://cloud.githubusercontent.com/assets/5373111/9166228/9618fd30-3f84-11e5-856e-dd0f61856406.png)
![image](https://cloud.githubusercontent.com/assets/5373111/9166423/0f1ddb2e-3f85-11e5-99b7-5ffc188c1760.png)

请问 为啥写上这个配置就会报错呢,看发布后的输出结果又是正常的.  问题出在哪?

**Comment by 2betop** [comment]
你确定是 loader 报出来的错，还是 seajsconf 插件报出来的错误？`fis3 release test -d ../test --verbose` 一把看看

**Comment by xjchenhao** [comment]
```
[DEBUG] 09:18:19.062 release style/aio.css >> /Users/chenhao/工程/钱庄网/test/style/aio_cc10410.css

 [DEBUG] 09:18:19.063 release sea-config.js >> /Users/chenhao/工程/钱庄网/test/sea-config_becfd9b.js

 [ERROR] unreleasable file [/Users/chenhao/工程/钱庄网/wap钱庄/app/views/includes/hdMeta.html]

 [DEBUG] 09:18:19.065 Error: unreleasable file [/Users/chenhao/工程/钱庄网/wap钱庄/app/views/includes/hdMeta.html]
    at Object.exports.error (/usr/local/lib/node_modules/fis3/lib/log.js:192:11)
    at Object.derive.getHashRelease (/usr/local/lib/node_modules/fis3/lib/file.js:488:15)
    at /usr/local/lib/node_modules/fis3/node_modules/fis3-deploy-local-deliver/index.js:68:22
    at Array.forEach (native)
    at module.exports (/usr/local/lib/node_modules/fis3/node_modules/fis3-deploy-local-deliver/index.js:67:12)
    at callPlugin (/usr/local/lib/node_modules/fis3/node_modules/fis3-command-release/lib/deploy.js:40:17)
    at /usr/local/lib/node_modules/fis3/node_modules/fis3-command-release/lib/deploy.js:95:21
    at wrapped (/usr/local/lib/node_modules/fis3/node_modules/fis3-command-release/lib/chains.js:30:58)
    at module.exports (/usr/local/lib/node_modules/fis3/node_modules/fis3-deploy-encoding/index.js:20:3)
    at callPlugin (/usr/local/lib/node_modules/fis3/node_modules/fis3-command-release/lib/deploy.js:40:17)

/usr/local/lib/node_modules/fis3/node_modules/fis3-command-release/lib/release.js:83
      throw e;
            ^
Error: unreleasable file [/Users/chenhao/工程/钱庄网/wap钱庄/app/views/includes/hdMeta.html]
    at Object.exports.error (/usr/local/lib/node_modules/fis3/lib/log.js:192:11)
    at Object.derive.getHashRelease (/usr/local/lib/node_modules/fis3/lib/file.js:488:15)
    at /usr/local/lib/node_modules/fis3/node_modules/fis3-deploy-local-deliver/index.js:68:22
    at Array.forEach (native)
    at module.exports (/usr/local/lib/node_modules/fis3/node_modules/fis3-deploy-local-deliver/index.js:67:12)
    at callPlugin (/usr/local/lib/node_modules/fis3/node_modules/fis3-command-release/lib/deploy.js:40:17)
    at /usr/local/lib/node_modules/fis3/node_modules/fis3-command-release/lib/deploy.js:95:21
    at wrapped (/usr/local/lib/node_modules/fis3/node_modules/fis3-command-release/lib/chains.js:30:58)
    at module.exports (/usr/local/lib/node_modules/fis3/node_modules/fis3-deploy-encoding/index.js:20:3)
    at callPlugin (/usr/local/lib/node_modules/fis3/node_modules/fis3-command-release/lib/deploy.js:40:17)
```

**Comment by xjchenhao** [comment]
是`seajsconfig`的问题吗?`sea-config.js`是它生成出来的.  但是`error`是在`hdMeta.html`上诶.
https://github.com/xjchenhao/fis-postpackager-seajs

**Comment by xjchenhao** [comment]
```
//.match('::package', {
    //    postpackager: fis.plugin('seajsconfig', {
    //        keyStrFilter: ['.js', 'app/script/'],
    //        domain: 'http://h5.test2.qian360.com'
    //    })
    //})
    .match('::package', {
        postpackager: fis.plugin('loader',null,'append')
    });
```
注释了依然出错哦😌
